stages:
  - test
  - build
  - stop
  - start



test:
  stage: test
  script:
    - pnpm install
    - pnpm turbo run test

build:
  stage: build
  script:
    - cp /etc/certs/root/root-ca.cert.pem ./root-ca.cert.pem
    - cp $ENV_PATH ./.env
    - docker build -t $CONTAINER_NAME .
  only:
    - main

stop:
  stage: stop
  script:
    - |-
      if [ "$(docker ps -qa -f name=$CONTAINER_NAME)" ]; then
        echo "Found container"
        if [ "$(docker ps -aq -f status=running -f name=$CONTAINER_NAME)" ]; then
            echo "Container is running, stopping now"
            docker stop $CONTAINER_NAME
        fi
        echo "Removing container"
        docker rm $CONTAINER_NAME
      fi
  only:
    - main
  only:
    - main

start:
  stage: start
  script:
    - docker run -p $PORT:$PORT --name $CONTAINER_NAME $DOCKER_FLAGS -d $CONTAINER_NAME
  only:
    - main
